# taking golang from docker library
FROM golang:1.22.4

# META DATA 
LABEL version="1.0" maintainer="imazlin"

# COPY NEEDED FILES
COPY containerProject /

# work repertory
WORKDIR /forumProject

# LAUNCH PORT
EXPOSE 15040
